server:
  type: simple
  connector:
    type: http
    port: 8080
  applicationContextPath: /
  requestLog:
      appenders: []

# Logging settings.
logging:
  level: WARN #DEBUG
  loggers:
    krestovsky.test: WARN
  appenders:
    - type: console

# Database settings
database:
  # the name of the JDBC driver
  driverClass: org.postgresql.Driver
  # the username
  user: postgres
  # the password
  password: 123
  # the JDBC URL
  url: jdbc:postgresql://localhost:5432/postgres
  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 1s
  # the SQL query to run when validating a connection's liveness
  validationQuery: "/* MyService Health Check */ SELECT 1"
  # the minimum number of connections to keep open
  minSize: 8
  # the maximum number of connections to keep open
  maxSize: 32
  # whether or not idle connections should be validated
  checkConnectionWhileIdle: true